# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase2App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postad',
            name='description',
        ),
        migrations.RemoveField(
            model_name='postad',
            name='email',
        ),
        migrations.RemoveField(
            model_name='postad',
            name='expire',
        ),
        migrations.RemoveField(
            model_name='postad',
            name='gist',
        ),
        migrations.AddField(
            model_name='postad',
            name='file1',
            field=models.FileField(default='/uploads/LuncClinical.csv', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='postad',
            name='file2',
            field=models.FileField(default='/uploads/LuncClinical.csv', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='postad',
            name='category',
            field=models.CharField(choices=[('svmg', 'SVM Gaussian'), ('svml', 'SVM Linear'), ('ann', 'ANN'), ('rfc', 'RFC')], max_length=3),
        ),
        migrations.AlterField(
            model_name='postad',
            name='location',
            field=models.CharField(choices=[('uni', 'univariate'), ('pca', 'pca')], max_length=3),
        ),
    ]
