# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase2App', '0003_auto_20170818_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postad',
            name='category',
        ),
        migrations.RemoveField(
            model_name='postad',
            name='location',
        ),
        migrations.RemoveField(
            model_name='postad',
            name='name',
        ),
        migrations.AlterField(
            model_name='postad',
            name='file1',
            field=models.FileField(default='/uploads/cosingerPhotoID.jpeg', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='postad',
            name='file2',
            field=models.FileField(default='/uploads/cosingerPhotoID.jpeg', upload_to='uploads/'),
        ),
    ]
