# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase2App', '0004_auto_20170819_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='postad',
            name='category',
            field=models.CharField(choices=[('svmg', 'SVM Gaussian'), ('svml', 'SVM Linear'), ('ann', 'ANN'), ('rfc', 'RFC')], default='svmg', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='postad',
            name='location',
            field=models.CharField(choices=[('uni', 'univariate'), ('pca', 'pca')], default='uni', max_length=500, null=True),
        ),
    ]
