# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phase2App', '0005_auto_20170819_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postad',
            name='category',
        ),
        migrations.RemoveField(
            model_name='postad',
            name='location',
        ),
    ]
