# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase2App', '0006_auto_20170819_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('svmg', 'SVM Gaussian'), ('svml', 'SVM Linear'), ('ann', 'ANN'), ('rfc', 'RFC')], default='svmg', max_length=500)),
                ('location', models.CharField(choices=[('uni', 'univariate'), ('pca', 'pca')], default='uni', max_length=500)),
            ],
        ),
    ]
